### ISSUE TITLE
ReferenceError: monaco is not defined

### ISSUE THREAD

**Issue by saikatstutorial** [pengx17/monaco-yaml#24] opened 2020-07-06 12:21 UTC
Getting "ReferenceError: monaco is not defined", though editor works fine with syntax highlight.
![image](https://user-images.githubusercontent.com/14033302/86591986-35717a00-bfb0-11ea-999c-50fde7670f31.png)

When component is destroyed, getting another error:
![image](https://user-images.githubusercontent.com/14033302/86592355-eaa43200-bfb0-11ea-94ce-939e409bf648.png)

even though I can mount the component again and it works as expected.

index.js
```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import './index.scss';
import App from "./app";

window.MonacoEnvironment = {
    getWorkerUrl(moduleId, label) {
        if (label === 'yaml') {
            return '../yaml.worker.bundle.js';
        }
        return '../editor.worker.bundle.js';
    },
};

ReactDOM.render(<App />, document.getElementById('root'));
```
YAMLEditor.js
```
import React, {useEffect, useState} from 'react';
import PropTypes from "prop-types";
import MonacoEditor from 'react-monaco-editor';
import 'monaco-yaml/esm/monaco.contribution';
import {languages} from 'monaco-editor/esm/vs/editor/editor.api';
import 'monaco-editor';

const {yaml} = languages || {};

const YAMLEditor = (props) => {
    const [value, setValue] = useState(props.yamlData);
    useEffect(() => {
        yaml &&
        yaml.yamlDefaults.setDiagnosticsOptions({
            validate: true,
            enableSchemaRequest: true,
            hover: true,
            completion: true
        });
    }, []);

    return (
        <MonacoEditor
            width="800"
            height="600"
            language="yaml"
            value={value}
            onChange={setValue}
        />
    );
};

YAMLEditor.propTypes = {
    // eslint-disable-next-line react/forbid-prop-types
    yamlData: PropTypes.any
};

export default YAMLEditor;
```
Usages in a **lazy loaded component**
```
<YAMLEditor yamlData={this.state.yamlRawContent} />
```
webpack entry and output:
```
entry: {
        main: './src/index.js',
        'editor.worker': 'monaco-editor/esm/vs/editor/editor.worker.js',
        'yaml.worker': 'monaco-yaml/esm/yaml.worker.js',
        'polyfill': '@babel/polyfill'
}

output: {
        path: path.resolve(__dirname, 'dist'),
        globalObject: 'this',
        publicPath: '/',
        filename: '[name].bundle.js'
}
```
package.json
```
"devDependencies": {
    "@babel/core": "7.2.2",
    "@babel/plugin-proposal-class-properties": "7.3.3",
    "@babel/plugin-transform-modules-commonjs": "7.4.0",
    "@babel/plugin-transform-runtime": "7.3.4",
    "@babel/preset-env": "7.7.1",
    "@babel/preset-react": "7.0.0",
    "babel-cli": "6.6.5",
    "babel-core": "6.26.3",
    "babel-eslint": "10.0.1",
    "babel-loader": "8.0.5",
    "compression-webpack-plugin": "^3.1.0",
    "copy-webpack-plugin": "^5.0.3",
    "cors": "^2.8.5",
    "cross-env": "^5.2.0",
    "css-loader": "^2.1.1",
    "enzyme": "3.9.0",
    "enzyme-adapter-react-16": "^1.11.2",
    "eslint": "^5.15.3",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-react": "^7.12.4",
    "eslint-watch": "^5.0.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "gulp": "^4.0.2",
    "gulp-connect": "^5.5.0",
    "gulp-nodemon": "^2.2.1",
    "html-webpack-plugin": "^3.2.0",
    "http-server": "^0.12.3",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^24.5.0",
    "jest-puppeteer": "^4.1.0",
    "json-update": "^4.0.0",
    "mini-css-extract-plugin": "^0.5.0",
    "node-sass": "^4.11.0",
    "npm-run-all": "^4.1.5",
    "postcss-loader": "2.0.7",
    "puppeteer": "^1.13.0",
    "react-loadable": "^5.5.0",
    "react-test-renderer": "^16.8.6",
    "redux-mock-store": "^1.5.3",
    "sass-loader": "6.0.6",
    "scss-loader": "0.0.1",
    "style-loader": "^0.23.1",
    "url-loader": "^1.1.2",
    "webpack": "^4.19.1",
    "webpack-async-chunk-names-plugin": "^0.1.1",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "^3.1.1",
    "webpack-dev-server": "^3.1.8"
  },
  "dependencies": {
    "@babel/polyfill": "^7.2.5",
    "@material-ui/core": "^3.9.2",
    "@material-ui/icons": "^3.0.2",
    "axios": "^0.18.0",
    "file-loader": "^3.0.1",
    "font-awesome": "^4.7.0",
    "history": "^4.9.0",
    "immutable": "^4.0.0-rc.12",
    "material-table": "1.34.2",
    "material-ui-slider": "^3.0.8",
    "monaco-yaml": "^2.4.0",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "monaco-editor": "^0.20.0",
    "react-monaco-editor": "^0.34.0",
    "react-redux": "^6.0.0",
    "react-router-dom": "^4.3.1",
    "react-slick": "^0.25.2",
    "react-swipeable-views": "^0.13.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.10.0",
    "redux-saga": "^1.0.2",
    "slick-carousel": "^1.8.1",
    "throttle-debounce": "^2.1.0",
    "yaml-js": "^0.2.3"
  }
```

**Comment by yazaabed** [comment] 2020-07-07 12:38
The order of the imports is wrong. I believe you need to load `import 'monaco-editor';` before you load the monaco-yaml code to define the monaco instance in wndow object.

**Comment by saikatstutorial** [comment] 2020-07-07 18:18
@yazaabed I just moved 'monaco-editor' up before 'monaco-yaml', still getting the same error. Also note that, I'm using this YAMLEditor component in a lazy loaded module.
```
import React, {useEffect, useState} from 'react';
import PropTypes from "prop-types";
import 'monaco-editor';
import MonacoEditor from 'react-monaco-editor';
import 'monaco-yaml/esm/monaco.contribution';
import {languages} from 'monaco-editor/esm/vs/editor/editor.api';

const {yaml} = languages || {};

window.MonacoEnvironment = {
    getWorkerUrl(moduleId, label) {
        if (label === 'yaml') {
            return '../yaml.worker.bundle.js';
        }
        return '../editor.worker.bundle.js';
    },
};

const YAMLEditor = (props) => {
    const [value, setValue] = useState(props.yamlData);
    useEffect(() => {
        yaml &&
        yaml.yamlDefaults.setDiagnosticsOptions({
            validate: true,
            enableSchemaRequest: true,
            hover: true,
            completion: true
        });
    }, []);

    return (
        <MonacoEditor
            width="800"
            height="600"
            language="yaml"
            value={value}
            onChange={setValue}
        />
    );
};

YAMLEditor.propTypes = {
    // eslint-disable-next-line react/forbid-prop-types
    yamlData: PropTypes.any
};

export default YAMLEditor;
```

**Comment by yazaabed** [comment] 2020-07-08 10:48
> ..

I have on my project monaco-editor as 0.18.0 and it is working fine with your config. Maybe can you try to run it with 0.18 instead of latest version?

**Comment by saikatstutorial** [comment] 2020-07-09 02:08
> > ..
> 
> I have on my project monaco-editor as 0.18.0 and it is working fine with your config. Maybe can you try to run it with 0.18 instead of latest version?

Tried with 0.18.0, code breaks with different error.
![image](https://user-images.githubusercontent.com/14033302/86988574-2b20cd00-c1b6-11ea-9bdc-2d5e806fb69d.png)

Then I downgraded to 0.17.1, which gives me same result as 0.20.0. 
However in both version if I keep **import 'monaco-editor'** in index.js (app bootstarp, though I really don't want to load monaco-editor on bootstrap), then "monaco is not defined" issue disappears and editor works well. But whenever YAMLEditor component unmounted, I get following error:
![image](https://user-images.githubusercontent.com/14033302/86988905-eea1a100-c1b6-11ea-9411-cef8bc15a6f3.png)

**Comment by yazaabed** [comment] 2020-07-10 10:44
I can show you how I did it to lazy load the monaco yaml editor by using es dynamic imports. Please check the example below:

```
// Lazy load monaco-editor by webpack dynamic-imports.
const monaco = await import(/* webpackChunkName: "editor.main" */"monaco-editor/esm/vs/editor/editor.api");

// @note: This is lazy-loading for css files, will be compiled at
// @ts-ignore
const styles = await import(/* webpackChunkName: "editor.styles" */"style-loader?injectType=lazyStyleTag!path/to/monaco/styles")

// Load styles on-demand.
this.styles = styles;
this.styles.use();

// Load monaco-yaml plugin
if (this.options.language === "yaml") {
    // @ts-ignore
    await import(/* webpackChunkName: "yaml.contribution" */"monaco-yaml/esm/monaco.contribution");

    // @ts-ignore
    const yamlWorkerUrl = await import(/* webpackChunkName: "yamlWorker.url" */"worker-plugin/loader?name=yaml&esModule!monaco-yaml/esm/yaml.worker");

    // monaco-editor add `MonacoEnvironment` to window object.
    const getWorkerUrl = (window as any).MonacoEnvironment.getWorkerUrl;

    // Add yaml worker to other workers provided by monaco-editor.
    (window as any).MonacoEnvironment.getWorkerUrl = (module: string, label: string) => {
        if (label === "yaml") {
            return yamlWorkerUrl.default;
        }

        return getWorkerUrl(module, label);
    };
}
```

And don't forget to add these two plugins in webpack configs:
- https://github.com/GoogleChromeLabs/worker-plugin
- https://github.com/microsoft/monaco-editor-webpack-plugin

```
new MonacoWebpackPlugin({
    languages: ["yaml"]
}),
new workerPlugin({
    globalObject: "self"
}),
```

**Comment by saikatstutorial** [comment] 2020-07-15 03:52
> await import(/* webpackChunkName: "editor.main" */"monaco-editor/esm/vs/editor/editor.api");

Where do you put following as you mentioned here https://github.com/pengx17/monaco-yaml/issues/24#issuecomment-654827214
```
await import("monaco-editor");
```

**Comment by saikatstutorial** [comment] 2020-07-15 04:38
Any idea when this PR will be merged https://github.com/pengx17/monaco-yaml/pull/23 ?

**Comment by yazaabed** [comment] 2020-07-15 19:03
> > await import(/* webpackChunkName: "editor.main" */"monaco-editor/esm/vs/editor/editor.api");
> 
> Where do you put following as you mentioned here [#24 (comment)](https://github.com/pengx17/monaco-yaml/issues/24#issuecomment-654827214)
> 
> ```
> await import("monaco-editor");
> ```

When you use `MonacoWebpackPlugin` you don't need to do `await import("monaco-editor");` you just do `await import(/* webpackChunkName: "editor.main" */"monaco-editor/esm/vs/editor/editor.api");`

**Comment by yazaabed** [comment] 2020-07-15 19:04
> Any idea when this PR will be merged #23 ?

It is merged already

**Comment by saikatstutorial** [comment] 2020-07-16 04:42
> > Any idea when this PR will be merged #23 ?
> 
> It is merged already

Thanks, can you please update npm registry https://www.npmjs.com/package/monaco-yaml

**Comment by saikatstutorial** [comment] 2020-07-17 05:19
> I can show you how I did it to lazy load the monaco yaml editor by using es dynamic imports. Please check the example below:
> 
> ```
> // Lazy load monaco-editor by webpack dynamic-imports.
> const monaco = await import(/* webpackChunkName: "editor.main" */"monaco-editor/esm/vs/editor/editor.api");
> 
> // @note: This is lazy-loading for css files
> const styles = await import(/* webpackChunkName: "editor.styles" */"style-loader?injectType=lazyStyleTag!path/to/monaco/styles")
> 
> // Load styles on-demand.
> this.styles = styles;
> this.styles.use();
> 
> // Don't forget to remove styles when destroy
> // this.styles.unuse();
> 
> // Load monaco-yaml plugin
> if (this.options.language === "yaml") {
>     await import(/* webpackChunkName: "yaml.contribution" */"monaco-yaml/esm/monaco.contribution");
> 
>     const yamlWorkerUrl = await import(/* webpackChunkName: "yamlWorker.url" */"worker-plugin/loader?name=yaml&esModule!monaco-yaml/esm/yaml.worker");
> 
>     // monaco-editor add `MonacoEnvironment` to window object.
>     const getWorkerUrl = (window as any).MonacoEnvironment.getWorkerUrl;
> 
>     // Add yaml worker to other workers provided by monaco-editor.
>     (window as any).MonacoEnvironment.getWorkerUrl = (module: string, label: string) => {
>         if (label === "yaml") {
>             return yamlWorkerUrl.default;
>         }
> 
>         return getWorkerUrl(module, label);
>     };
> }
> ```
> 
> And don't forget to add these two plugins in webpack configs:
> 
> * https://github.com/GoogleChromeLabs/worker-plugin
> * https://github.com/microsoft/monaco-editor-webpack-plugin
> 
> ```
> new MonacoWebpackPlugin({
>     languages: ["yaml"]
> }),
> new workerPlugin({
>     globalObject: "self"
> }),
> ```

Implemented the above, now there is no error. But language service seems not working.
webpack:
```
const HtmlWebPackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const WorkerPlugin = require('worker-plugin');
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
const path = require("path");
const htmlWebpackPlugin = new HtmlWebPackPlugin({
    template: "./src/index.html",
    filename: "./index.html"
});

const MONACO_DIR = path.resolve(__dirname, './node_modules/monaco-editor');

module.exports = {
    entry: {
        main: './src/index.js',
        'polyfill': '@babel/polyfill',
        /*'editor.worker': 'monaco-editor/esm/vs/editor/editor.worker.js',
        'yaml.worker': 'monaco-yaml/esm/yaml.worker.js',*/
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                exclude: MONACO_DIR,
                use: ['style-loader', MiniCssExtractPlugin.loader, 'css-loader']
            },
            {
                test: /\.scss$/,
                exclude: MONACO_DIR,
                use: ['style-loader', MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader']
            },
            {
                test: /\.css$/,
                include: MONACO_DIR,
                use: ['style-loader', MiniCssExtractPlugin.loader, 'css-loader']
            },
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader"
                }
            },
            {
                test: /\.(jpe?g|png|gif|svg)$/i,
                loader: 'file-loader',
                options: {
                    name: '[path][name].[ext]',
                    publicPath: '../',
                    useRelativePaths: true
                }
            },
            {
                test: /\.(woff|woff2|eot|ttf)$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: './font/[hash].[ext]',
                    mimetype: 'application/font-woff'
                }
            }
        ]
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        publicPath: '/',
        filename: '[name].bundle.js'
    },
    devServer: {
        disableHostCheck: true,
        historyApiFallback: true,
        host: 'localhost',
        port: 8080
    },
    devtool: 'source-map',
    plugins: [
        htmlWebpackPlugin,
        new MiniCssExtractPlugin({filename: 'style.css'}),
        new MonacoWebpackPlugin({
            languages: ["yaml"]
        }),
        new WorkerPlugin({
            globalObject: "self"
        })
    ]
};

```
yaml editor
```
import React, {useEffect, useState} from 'react';
import PropTypes from "prop-types";
import 'monaco-editor';
import MonacoEditor from 'react-monaco-editor';

const load = async () => {
    const monaco = await import("monaco-editor/esm/vs/editor/editor.api");
    await import("monaco-yaml/esm/monaco.contribution");
    const yamlWorkerUrl = await import("worker-plugin/loader?name=yaml&esModule!monaco-yaml/esm/yaml.worker");

    const getWorkerUrl = window.MonacoEnvironment.getWorkerUrl;

    window.MonacoEnvironment = {
        getWorkerUrl(module, label) {
            console.log("getWorkerUrl", label);
            if (label === 'yaml') {
                return yamlWorkerUrl.default;
            }
            return getWorkerUrl(module, label);
        },
    };

    return monaco;
};


const YAMLEditor = (props) => {
    const [value, setValue] = useState(props.yamlData);

    useEffect(() => {
        load().then(monaco => {
            console.log("loaded", monaco.languages.yaml);
            const {yaml} = monaco.languages || {};
            yaml &&
            yaml.yamlDefaults.setDiagnosticsOptions({
                validate: true,
                enableSchemaRequest: false,
                hover: true,
                completion: true,
                schemas: [
                    {
                        fileMatch: ['*'],
                        schema: {
                            type: 'object',
                            properties: {
                                prop: {
                                    enum: [true, false],
                                },
                            },
                        },
                    }
                ]
            });
        });
    }, []);

    return (
        <MonacoEditor
            width="800"
            height="600"
            language="yaml"
            value={value}
            onChange={setValue}
        />
    );
};

YAMLEditor.propTypes = {
    yamlData: PropTypes.any
};

export default YAMLEditor;
```

Any idea why getting this warning during compile?
![image](https://user-images.githubusercontent.com/14033302/87751000-9acc3300-c81a-11ea-9d87-5a4f2d6d91bd.png)

Can you please share a complete example with lazy loading?

**Comment by yazaabed** [comment] 2020-07-17 10:03
> > I can show you how I did it to lazy load the monaco yaml editor by using es dynamic imports. Please check the example below:
> > ```
> > // Lazy load monaco-editor by webpack dynamic-imports.
> > const monaco = await import(/* webpackChunkName: "editor.main" */"monaco-editor/esm/vs/editor/editor.api");
> > 
> > // @note: This is lazy-loading for css files
> > const styles = await import(/* webpackChunkName: "editor.styles" */"style-loader?injectType=lazyStyleTag!path/to/monaco/styles")
> > 
> > // Load styles on-demand.
> > this.styles = styles;
> > this.styles.use();
> > 
> > // Don't forget to remove styles when destroy
> > // this.styles.unuse();
> > 
> > // Load monaco-yaml plugin
> > if (this.options.language === "yaml") {
> >     await import(/* webpackChunkName: "yaml.contribution" */"monaco-yaml/esm/monaco.contribution");
> > 
> >     const yamlWorkerUrl = await import(/* webpackChunkName: "yamlWorker.url" */"worker-plugin/loader?name=yaml&esModule!monaco-yaml/esm/yaml.worker");
> > 
> >     // monaco-editor add `MonacoEnvironment` to window object.
> >     const getWorkerUrl = (window as any).MonacoEnvironment.getWorkerUrl;
> > 
> >     // Add yaml worker to other workers provided by monaco-editor.
> >     (window as any).MonacoEnvironment.getWorkerUrl = (module: string, label: string) => {
> >         if (label === "yaml") {
> >             return yamlWorkerUrl.default;
> >         }
> > 
> >         return getWorkerUrl(module, label);
> >     };
> > }
> > ```
> > 
> > 
> > And don't forget to add these two plugins in webpack configs:
> > 
> > * https://github.com/GoogleChromeLabs/worker-plugin
> > * https://github.com/microsoft/monaco-editor-webpack-plugin
> > 
> > ```
> > new MonacoWebpackPlugin({
> >     languages: ["yaml"]
> > }),
> > new workerPlugin({
> >     globalObject: "self"
> > }),
> > ```
> 
> Implemented the above, now there is no error. But language service seems not working.
> webpack:
> 
> ```
> const HtmlWebPackPlugin = require("html-webpack-plugin");
> const MiniCssExtractPlugin = require("mini-css-extract-plugin");
> const WorkerPlugin = require('worker-plugin');
> const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
> const path = require("path");
> const htmlWebpackPlugin = new HtmlWebPackPlugin({
>     template: "./src/index.html",
>     filename: "./index.html"
> });
> 
> const MONACO_DIR = path.resolve(__dirname, './node_modules/monaco-editor');
> 
> module.exports = {
>     entry: {
>         main: './src/index.js',
>         'polyfill': '@babel/polyfill',
>         /*'editor.worker': 'monaco-editor/esm/vs/editor/editor.worker.js',
>         'yaml.worker': 'monaco-yaml/esm/yaml.worker.js',*/
>     },
>     module: {
>         rules: [
>             {
>                 test: /\.css$/,
>                 exclude: MONACO_DIR,
>                 use: ['style-loader', MiniCssExtractPlugin.loader, 'css-loader']
>             },
>             {
>                 test: /\.scss$/,
>                 exclude: MONACO_DIR,
>                 use: ['style-loader', MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader']
>             },
>             {
>                 test: /\.css$/,
>                 include: MONACO_DIR,
>                 use: ['style-loader', MiniCssExtractPlugin.loader, 'css-loader']
>             },
>             {
>                 test: /\.(js|jsx)$/,
>                 exclude: /node_modules/,
>                 use: {
>                     loader: "babel-loader"
>                 }
>             },
>             {
>                 test: /\.(jpe?g|png|gif|svg)$/i,
>                 loader: 'file-loader',
>                 options: {
>                     name: '[path][name].[ext]',
>                     publicPath: '../',
>                     useRelativePaths: true
>                 }
>             },
>             {
>                 test: /\.(woff|woff2|eot|ttf)$/,
>                 loader: 'url-loader',
>                 options: {
>                     limit: 10000,
>                     name: './font/[hash].[ext]',
>                     mimetype: 'application/font-woff'
>                 }
>             }
>         ]
>     },
>     output: {
>         path: path.resolve(__dirname, 'dist'),
>         publicPath: '/',
>         filename: '[name].bundle.js'
>     },
>     devServer: {
>         disableHostCheck: true,
>         historyApiFallback: true,
>         host: 'localhost',
>         port: 8080
>     },
>     devtool: 'source-map',
>     plugins: [
>         htmlWebpackPlugin,
>         new MiniCssExtractPlugin({filename: 'style.css'}),
>         new MonacoWebpackPlugin({
>             languages: ["yaml"]
>         }),
>         new WorkerPlugin({
>             globalObject: "self"
>         })
>     ]
> };
> ```
> 
> yaml editor
> 
> ```
> import React, {useEffect, useState} from 'react';
> import PropTypes from "prop-types";
> import 'monaco-editor';
> import MonacoEditor from 'react-monaco-editor';
> 
> const load = async () => {
>     const monaco = await import("monaco-editor/esm/vs/editor/editor.api");
>     await import("monaco-yaml/esm/monaco.contribution");
>     const yamlWorkerUrl = await import("worker-plugin/loader?name=yaml&esModule!monaco-yaml/esm/yaml.worker");
> 
>     const getWorkerUrl = window.MonacoEnvironment.getWorkerUrl;
> 
>     window.MonacoEnvironment = {
>         getWorkerUrl(module, label) {
>             console.log("getWorkerUrl", label);
>             if (label === 'yaml') {
>                 return yamlWorkerUrl.default;
>             }
>             return getWorkerUrl(module, label);
>         },
>     };
> 
>     return monaco;
> };
> 
> 
> const YAMLEditor = (props) => {
>     const [value, setValue] = useState(props.yamlData);
> 
>     useEffect(() => {
>         load().then(monaco => {
>             console.log("loaded", monaco.languages.yaml);
>             const {yaml} = monaco.languages || {};
>             yaml &&
>             yaml.yamlDefaults.setDiagnosticsOptions({
>                 validate: true,
>                 enableSchemaRequest: false,
>                 hover: true,
>                 completion: true,
>                 schemas: [
>                     {
>                         fileMatch: ['*'],
>                         schema: {
>                             type: 'object',
>                             properties: {
>                                 prop: {
>                                     enum: [true, false],
>                                 },
>                             },
>                         },
>                     }
>                 ]
>             });
>         });
>     }, []);
> 
>     return (
>         <MonacoEditor
>             width="800"
>             height="600"
>             language="yaml"
>             value={value}
>             onChange={setValue}
>         />
>     );
> };
> 
> YAMLEditor.propTypes = {
>     yamlData: PropTypes.any
> };
> 
> export default YAMLEditor;
> ```
> 
> Any idea why getting this warning during compile?
> ![image](https://user-images.githubusercontent.com/14033302/87751000-9acc3300-c81a-11ea-9d87-5a4f2d6d91bd.png)
> 
> Can you please share a complete example with lazy loading?

Does the editor loaded fine? Because this is a warning from worker-plugin it means the editor should shown? If you want you can do what is here in the link `https://github.com/pengx17/monaco-yaml/issues/20` which allow you to remove even this code at all and the monaco plugin will handle it for you.

```
const load = async () => {
    const monaco = await import("monaco-editor/esm/vs/editor/editor.api");
    await import("monaco-yaml/esm/monaco.contribution");
    const yamlWorkerUrl = await import("worker-plugin/loader?name=yaml&esModule!monaco-yaml/esm/yaml.worker");

    const getWorkerUrl = window.MonacoEnvironment.getWorkerUrl;

    window.MonacoEnvironment = {
        getWorkerUrl(module, label) {
            console.log("getWorkerUrl", label);
            if (label === 'yaml') {
                return yamlWorkerUrl.default;
            }
            return getWorkerUrl(module, label);
        },
    };

    return monaco;
};
```

**Comment by yazaabed** [comment] 2020-10-08 08:59
Can we close this issue?

**Comment by tnir** [comment] 2021-05-07 06:10
@yazaabed I think we need to merge #48 before closing this.

**Comment by remcohaszing** [comment] 2021-05-07 06:40
> @yazaabed I think we need to merge #48 before closing this.

No, this issue is caused by a wrong setup. #48 also closes this issue, because it no longer uses the global monaco which is the cause for this issue.

**Comment by JounQin** [comment] 2021-05-26 06:04
Workaround from `monaco-editor-webpack-plugin`: `globalAPI` option.

See also: https://github.com/microsoft/monaco-editor-webpack-plugin#options

**Closed** 2021-07-17 10:46 UTC
